### ISSUE TITLE
Add search / filter function

### ISSUE THREAD

**Issue by SyleKu** [i4Ds/HpcSchedulingSystem#10]
A user should be able to search / filter it's own job list

**Comment by marco-willi** [comment]
Maybe it would also be helpful to color the different job panels according to their status. This would help to quickly identify running jobs in order to avoid mistakenly having running jobs that are no longer needed.

![grafik](https://user-images.githubusercontent.com/19252323/93862609-9745a400-fcc2-11ea-909a-0f2b1c1c4486.png)
